SELECT B.ID,
(
    CASE
        WHEN B.COLONY_LEVEL = 1 THEN 'CRITICAL'
        WHEN B.COLONY_LEVEL = 2 THEN 'HIGH'
        WHEN B.COLONY_LEVEL = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END
) AS 'COLONY_NAME'
FROM 
    (SELECT ID, NTILE(4)
    OVER(ORDER BY SIZE_OF_COLONY DESC) AS "COLONY_LEVEL"
    FROM ECOLI_DATA) AS B
    ORDER BY B.ID