SELECT F.ID AS ID, N.FISH_NAME AS FISH_NAME, F.LENGTH AS LENGTH
FROM (
    SELECT FI.FISH_TYPE, MAX(FI.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO FI
    WHERE FI.LENGTH > 10
    GROUP BY FI.FISH_TYPE
) AS MaxFish
JOIN FISH_INFO F ON MaxFish.FISH_TYPE = F.FISH_TYPE AND MaxFish.MAX_LENGTH = F.LENGTH
JOIN FISH_NAME_INFO N ON F.FISH_TYPE = N.FISH_TYPE
ORDER BY ID;