SELECT 
    INFO.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS INFO, REST_REVIEW AS REVIEW
WHERE INFO.REST_ID = REVIEW.REST_ID
AND ADDRESS LIKE "서울%"
GROUP BY INFO.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC