SELECT
    INFO.ITEM_ID,
    INFO.ITEM_NAME,
    INFO.RARITY
FROM
    ITEM_INFO INFO,
    ITEM_TREE TREE
WHERE
    INFO.ITEM_ID = TREE.ITEM_ID
AND
    TREE.PARENT_ITEM_ID
IN
    (SELECT ITEM_INFO.ITEM_ID FROM ITEM_INFO WHERE ITEM_INFO.RARITY = 'RARE')
ORDER BY INFO.ITEM_ID DESC