SELECT
    HR_GRADE.TOTAL_SCORE AS SCORE,
    HR_GRADE.EMP_NO,
    HR_EMPLOYEES.EMP_NAME,
    HR_EMPLOYEES.POSITION,
    HR_EMPLOYEES.EMAIL
FROM
    (SELECT
        EMP_NO,
        SUM(SCORE) AS TOTAL_SCORE
    FROM
        HR_GRADE
    WHERE
        YEAR = 2022
    GROUP BY
        EMP_NO)
    HR_GRADE
JOIN
    HR_EMPLOYEES
ON
    HR_GRADE.EMP_NO = HR_EMPLOYEES.EMP_NO
ORDER BY
    HR_GRADE.TOTAL_SCORE DESC
LIMIT 1;
    